# Generated by Django 4.1.7 on 2023-06-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_left_banner', models.ImageField(blank=True, default='top_left_banner', null=True, upload_to='banners/')),
                ('top_right_banner', models.ImageField(blank=True, default='top_right_banner', null=True, upload_to='banners/')),
                ('bottom_right_banner', models.ImageField(blank=True, default='bottom_right_banner', null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('blog_link', models.CharField(default='', max_length=500, unique=True)),
                ('blog_clean_link', models.CharField(default='', max_length=500)),
                ('blog_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_image', models.ImageField(blank=True, default='', null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousal_home_main', models.ImageField(blank=True, default='', null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, default='', null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBuilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_code', models.CharField(max_length=50, unique=True)),
                ('cus_processor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_cpu_cooler', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_motherbrd', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_ram', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_hardisk', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_gpu', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_powersupply', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_cabinet', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cus_desc', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('cus_additional', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('status', models.CharField(blank=True, default='In Cart', max_length=50, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('cus_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreBuilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_name', models.CharField(max_length=255)),
                ('modal_code', models.CharField(max_length=50, unique=True)),
                ('modal_cpu', models.CharField(max_length=50)),
                ('modal_monitor', models.CharField(max_length=50)),
                ('modal_ram', models.CharField(max_length=50)),
                ('modal_motherbrd', models.CharField(max_length=50)),
                ('modal_gpu', models.CharField(max_length=50)),
                ('modal_ssd', models.CharField(max_length=50)),
                ('modal_storage_rom', models.CharField(max_length=50)),
                ('modal_smps', models.CharField(max_length=50)),
                ('modal_offer', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
                ('product_image_1', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
                ('product_image_2', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
                ('product_image_3', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
                ('product_image_4', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
                ('product_image_5', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pass_word', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='', null=True, upload_to='profile_pictures/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('account_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_code', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
                ('sub_total', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('paid', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('due', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('biller', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('brand', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('special', models.BooleanField(default=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('product_quantity', models.CharField(max_length=500)),
                ('price', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('customer_id', models.CharField(max_length=50)),
                ('prebuilt_id', models.CharField(blank=True, default='NoID', max_length=50, null=True)),
                ('prebuilt_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='In Cart', max_length=50, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
    ]
