from django.contrib import admin
from django.urls import re_path,include
from django.urls import path
from App import views

urlpatterns = [

#------------------USER MODULE URLS-------------------------------------#

    re_path(r'^$', views.indexZero, name='indexZero'),
    re_path(r'^index/$', views.index, name='index'),
    re_path(r'^allProducts/$', views.allProducts, name='allProducts'),
    re_path(r'^contact/$', views.contact, name='contact'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^view/(?P<id>\d+)$', views.view, name='view'),
    re_path(r'^uregister/$', views.uregister, name='uregister'),
    re_path(r'^loginform/$', views.loginform, name='loginform'),
    re_path(r'^mainIndex/$', views.mainIndex, name='mainIndex'),
    re_path(r'^home/$', views.home, name='home'),
    re_path(r'^add_to_cart_form/(?P<id>\d+)$', views.add_to_cart_form, name='add_to_cart_form'),
    re_path(r'^cartDelete/(?P<id>\d+)$', views.cartDelete, name='cartDelete'),
    re_path(r'^cusDelete/(?P<id>\d+)$', views.cusDelete, name='cusDelete'),
    re_path(r'^cartQuaAdd/(?P<id>\d+)$', views.cartQuaAdd, name='cartQuaAdd'),
    re_path(r'^categoryFilter/(?P<id>\d+)$', views.categoryFilter, name='categoryFilter'),
    re_path(r'^cart/$', views.cart, name='cart'),
    re_path(r'^preBuiltHome/$', views.preBuiltHome, name='preBuiltHome'),
    re_path(r'^productsHome/$', views.productsHome, name='productsHome'),
    re_path(r'^contactHome/$', views.contactHome, name='contactHome'),
    re_path(r'^pcbAddForm/$', views.pcbAddForm, name='pcbAddForm'),
    re_path(r'^addToCartPreBuilt/(?P<id>\d+)$', views.addToCartPreBuilt, name='addToCartPreBuilt'),
    re_path(r'^pcbAddFormEdit/(?P<id>\d+)$', views.pcbAddFormEdit, name='pcbAddFormEdit'),
    re_path(r'^checkOut/$', views.checkOut, name='checkOut'),
    re_path(r'^logout/$', views.logout, name='logout'),


#------------------ADMIN MODULE URLS------------------------------------#

    re_path(r'^adminIndex/$', views.adminIndex, name='adminIndex'),
    re_path(r'^adminDash/$', views.adminDash, name='adminDash'),
    re_path(r'^productList/$', views.productList, name='productList'),
    re_path(r'^addProduct/$', views.addProduct, name='addProduct'),
    re_path(r'^categoryList/$', views.categoryList, name='categoryList'),
    re_path(r'^addCategory/$', views.addCategory, name='addCategory'),
    re_path(r'^adminProfile/$', views.adminProfile, name='adminProfile'),
    re_path(r'^editSales/$', views.editSales, name='editSales'),
    re_path(r'^salesDetails/(?P<id>\d+)$', views.salesDetails, name='salesDetails'),
    re_path(r'^salesList/$', views.salesList, name='salesList'),
    re_path(r'^addBanner/$', views.addBanner, name='addBanner'),
    re_path(r'^sideBanners/$', views.sideBanners, name='sideBanners'),
    re_path(r'^add_sideBanners_form/(?P<id>\d+)$', views.add_sideBanners_form, name='add_sideBanners_form'),
    re_path(r'^add_carousal_form/$', views.add_carousal_form, name='add_carousal_form'),
    re_path(r'^deleteBanner/(?P<id>\d+)$', views.deleteBanner, name='deleteBanner'),
    re_path(r'^deleteBlog/(?P<id>\d+)$', views.deleteBlog, name='deleteBlog'),
    re_path(r'^deleteCategory/(?P<id>\d+)$', views.deleteCategory, name='deleteCategory'),
    re_path(r'^delete_sideBanners/(?P<id>\d+)$', views.delete_sideBanners, name='delete_sideBanners'),
    re_path(r'^msg_banner/$', views.msg_banner, name='msg_banner'),
    re_path(r'^cat_del_msg/$', views.cat_del_msg, name='cat_del_msg'),
    re_path(r'^blog_del_msg/$', views.blog_del_msg, name='blog_del_msg'),
    re_path(r'^editCategory/(?P<id>\d+)$', views.editCategory, name='editCategory'),
    re_path(r'^addcategory_form/$', views.addcategory_form, name='addcategory_form'),
    re_path(r'^edit_category_form/(?P<id>\d+)$', views.edit_category_form, name='edit_category_form'),
    re_path(r'^editProductForm/(?P<id>\d+)$', views.editProductForm, name='editProductForm'),
    re_path(r'^editProduct/(?P<id>\d+)$', views.editProduct, name='editProduct'),
    re_path(r'^deleteProduct/(?P<id>\d+)$', views.deleteProduct, name='deleteProduct'),
    re_path(r'^deleteBrand/(?P<id>\d+)$', views.deleteBrand, name='deleteBrand'),
    re_path(r'^addProductForm/$', views.addProductForm, name='addProductForm'),
    re_path(r'^pro_del_msg/$', views.pro_del_msg, name='pro_del_msg'),
    re_path(r'^productDetails/(?P<id>\d+)$', views.productDetails, name='productDetails'),
    re_path(r'^editBlogs/(?P<id>\d+)$', views.editBlogs, name='editBlogs'),
    re_path(r'^editBlogsForm/(?P<id>\d+)$', views.editBlogsForm, name='editBlogsForm'),
    re_path(r'^actdea$', views.actdea, name='actdea'),
    re_path(r'^actsts$', views.actsts, name='actsts'),
    re_path(r'^addBlogs$', views.addBlogs, name='addBlogs'),
    re_path(r'^addBlogsForm$', views.addBlogsForm, name='addBlogsForm'),
    re_path(r'^addBrand$', views.addBrand, name='addBrand'),
    re_path(r'^addBrand_Form$', views.addBrand_Form, name='addBrand_Form'),
    re_path(r'^preBuilt$', views.preBuilt, name='preBuilt'),
    re_path(r'^addpreBuiltForm$', views.addpreBuiltForm, name='addpreBuiltForm'),
    re_path(r'^viewpreBuilt$', views.viewpreBuilt, name='viewpreBuilt'),
    re_path(r'^viewPrebuiltDetails/(?P<id>\d+)$', views.viewPrebuiltDetails, name='viewPrebuiltDetails'),
    re_path(r'^editPreBuilt/(?P<id>\d+)$', views.editPreBuilt, name='editPreBuilt'),
    re_path(r'^editpreBuiltForm/(?P<id>\d+)$', views.editpreBuiltForm, name='editpreBuiltForm'),
    re_path(r'^pre_img_del/(?P<id>\d+)$', views.pre_img_del, name='pre_img_del'),
    re_path(r'^pre_img_del_1/(?P<id>\d+)$', views.pre_img_del_1, name='pre_img_del_1'),
    re_path(r'^pre_img_del_2/(?P<id>\d+)$', views.pre_img_del_2, name='pre_img_del_2'),
    re_path(r'^pre_img_del_3/(?P<id>\d+)$', views.pre_img_del_3, name='pre_img_del_3'),
    re_path(r'^pre_img_del_4/(?P<id>\d+)$', views.pre_img_del_4, name='pre_img_del_4'),
    re_path(r'^pre_img_del_5/(?P<id>\d+)$', views.pre_img_del_5, name='pre_img_del_5'),
    re_path(r'^deletePreBuilt/(?P<id>\d+)$', views.deletePreBuilt, name='deletePreBuilt'),
    re_path(r'^editPreBuilt_post_del$', views.editPreBuilt_post_del, name='editPreBuilt_post_del'),
    re_path(r'^pre_actdea$', views.pre_actdea, name='pre_actdea'),

    re_path(r'^pcb/$', views.pcb, name='pcb'),
    re_path(r'^pcbCustom/$', views.pcbCustom, name='pcbCustom'),

]
